### ISSUE TITLE
Temporary workaround for Vanilla HTML projects?

### ISSUE THREAD

**Issue by binarykitchen** [rspack-contrib/storybook-rsbuild#131]
I understand, Vanilla HTML support is scheduled for later in your [Roadmap](https://github.com/rspack-contrib/storybook-rsbuild#features).

But I need it now :)

So, wondering if there is a hack or workaround to run it on Vanilla HTML using the storybook-builder-rsbuild package alone?

**Comment by binarykitchen** [comment]
Nice, thank you @fi3ework I'll check it out asap

**Comment by binarykitchen** [comment]
Most works very well. One little feedback @fi3ework 

```ts
name: getAbsolutePath('storybook-html-rsbuild'),
```

That function `getAbsolutePath` isn't needed, it works without.

Then I would point it to the rsbuild configuration like that for example:

```
  framework: {
    name: "storybook-html-rsbuild",
    options: {
      builder: {
        rsbuildConfigPath: "etc/rsbuild/config.ts",
      },
    },
  },
```

**Comment by fi3ework** [comment]
> That function getAbsolutePath isn't needed, it works without.

It's necessary only when no hoist is allowed.

**Comment by binarykitchen** [comment]
I see.

Add to documentation maybe?
