### ISSUE TITLE
Cannot destructure property 'default' of 'moduleExports' as it is undefined

### ISSUE THREAD

**Issue by NajamShehzad** [rspack-contrib/storybook-rsbuild#15]
When running sandbox example its throwing error, same error in my working project when replace @storybook/react-webpack5 with  storybook-react-rsbuild 

![image](https://github.com/rspack-contrib/storybook-rsbuild/assets/37629243/34054637-4e25-4d9d-9ed8-cb7e95d5d361)

**Comment by fi3ework** [comment]
I can't reproduce the error in with sandbox demo in this repository. Could you provide a minimal repository to help troubleshooting this issue?

**Comment by fi3ework** [comment]
I cloned the repository and installed the dep then run `pnpm storybook`, it works well. I'm not sure what's happening, you could run ` pnpx envinfo --system --npmPackages --binaries --browsers` to report your node and pnpm version.

<img width="1856" alt="image" src="https://github.com/rspack-contrib/storybook-rsbuild/assets/12322740/e7432821-2df5-4aa7-911c-5c90609948d0">

**Comment by NajamShehzad** [comment]
This is the output of  pnpx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 615.48 MB / 31.70 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @chromatic-com/storybook: ^1.4.0 => 1.5.0
    @rsbuild/core: 0.6.15 => 0.7.1
    @rsbuild/plugin-react: ^0.6.2 => 0.7.1
    @storybook/addon-essentials: 8.1.1 => 8.1.1
    @storybook/addon-interactions: 8.1.1 => 8.1.1
    @storybook/addon-links: 8.1.1 => 8.1.1
    @storybook/addon-onboarding: 8.1.1 => 8.1.1
    @storybook/blocks: 8.1.1 => 8.1.1
    @storybook/react: 8.1.1 => 8.1.1
    @storybook/test: 8.1.1 => 8.1.1
    @types/react: ^18 => 18.3.3
    @types/react-dom: ^18 => 18.3.0
    react: 18 => 18.3.1
    react-dom: 18 => 18.3.1
    storybook: 8.1.1 => 8.1.1
    storybook-react-rsbuild: 0.0.4 => 0.0.4
    typescript: ^5.3.2 => 5.4.5

It can be issue with my machine? maybe, I have another machine I can try to run on that one

**Comment by fi3ework** [comment]
It might be a bug when using rsbuild 0.7 with Windows. Could you try to install rsbuild@0.6.15 or use an Mac/Linux machine?

**Comment by fi3ework** [comment]
Does `storybook build` works fine on Windows?

**Comment by NajamShehzad** [comment]
The build process run successfully but when I access the story it shows the same error. this time Im using different windows machine

![image](https://github.com/rspack-contrib/storybook-rsbuild/assets/37629243/e0d255d8-0983-4385-b059-31eee4efb413)


  **System**:
    OS: Windows 11 10.0.26120
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 29.28 GB / 47.91 GB
  **Binaries**:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.11 - ~\AppData\Local\pnpm\pnpm.CMD
  **Browsers**:
    Edge: Chromium (126.0.2592.13)
    Internet Explorer: 11.0.26100.1
  **npmPackages**:
    @chromatic-com/storybook: ^1.4.0 => 1.4.0
    @rsbuild/core: 0.6.15 => 0.6.15
    @rsbuild/plugin-react: ^0.6.2 => 0.6.2
    @storybook/addon-essentials: 8.1.1 => 8.1.1
    @storybook/addon-interactions: 8.1.1 => 8.1.1
    @storybook/addon-links: 8.1.1 => 8.1.1
    @storybook/addon-onboarding: 8.1.1 => 8.1.1
    @storybook/blocks: 8.1.1 => 8.1.1
    @storybook/react: 8.1.1 => 8.1.1
    @storybook/test: 8.1.1 => 8.1.1
    @types/react: ^18 => 18.0.0
    @types/react-dom: ^18 => 18.0.0
    react: 18 => 18.0.0
    react-dom: 18 => 18.0.0
    storybook: 8.1.1 => 8.1.1
    storybook-react-rsbuild: 0.0.4 => 0.0.4
    typescript: ^5.3.2 => 5.3.2

**Comment by fi3ework** [comment]
This issue should not relate to Rsbuild, but with https://github.com/rspack-contrib/storybook-rsbuild/blob/main/packages/builder-rsbuild/src/preview/virtual-module-mapping.ts/#L155, which only handles a POSIX style path. I'll try to get a Windows machine and fix the issue later.

**Comment by fi3ework** [comment]
0.0.5 should works on Windows now.

**Comment by NajamShehzad** [comment]
> 0.0.5 should works on Windows now.

Working perfect, Thanks 😊
