### ISSUE TITLE
compatibility with @storybook/addon-coverage

### ISSUE THREAD

**Issue by njzydark** [rspack-contrib/storybook-rsbuild#160]
When using the [@storybook/addon-coverage](https://storybook.js.org/addons/@storybook/addon-coverage) plugin to obtain code coverage, the output does not include any test files. According to the plugin documentation, it appears to support Webpack or Vite.

**Comment by fi3ework** [comment]
Minimal reproduction or any clue please?

**Comment by njzydark** [comment]
> Minimal reproduction or any clue please?

https://github.com/njzydark/storybook-rsbuild-demo

**Comment by fi3ework** [comment]
I'll check it later today.

**Comment by fi3ework** [comment]
1. According to https://storybook.rsbuild.dev/guide/options/builder-options.html#using-customized-addon, you need to add it to `options.webpackAddons`, and use with `getAbsolutePath` for resolving the addon correct path.

```diff
import type { StorybookConfig } from 'storybook-react-rsbuild';
import { dirname, join } from 'node:path';

+function getAbsolutePath(value: string): any {
+  return dirname(require.resolve(join(value, 'package.json')));
+}

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-onboarding',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
-    // '@storybook/addon-coverage',
  ],
+  webpackAddons: [
+    {
+      name: getAbsolutePath('@storybook/addon-coverage'),
+      options: {
+        istanbul: {
+          include: ['src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
+          exclude: [],
+        },
+      },
+    },
+  ],
  framework: {
    name: 'storybook-react-rsbuild',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  typescript: {
    reactDocgen: 'react-docgen-typescript',
    check: true,
  },
};

export default config;
```

2. Correct the script

```diff
- "test-storybook-coverage": "test-storybook -- --coverage"
+ "test-storybook-coverage": "test-storybook --coverage"
```

3. There you go

<img width="473" alt="image" src="https://github.com/user-attachments/assets/b203b40d-8024-4a3c-8e49-18880a2fff7d">
