### ISSUE TITLE
[Feature]: Support webcomponent

### ISSUE THREAD

**Issue by dennyak47** [rspack-contrib/storybook-rsbuild#190]
### What problem does this feature solve?

Support webcomponent, so the story render function can support:
```ts
import {html} from "lit"
const primary = {
  render:()=>html`<my-component></my-component>`
}
```

### What does the proposed API look like?

```ts
import {html} from "lit"
const primary = {
  render:()=>html`<my-component></my-component>`
}
```

**Comment by fi3ework** [comment]
Which lit version you're using?

**Comment by dennyak47** [comment]
I am using lit 3.

**Comment by dennyak47** [comment]
> Which lit version you're using?

I am using lit 3
