### ISSUE TITLE
Unable to resolve package with source build plugin in a monorepo

### ISSUE THREAD

**Issue by yf-yang** [rspack-contrib/storybook-rsbuild#24]
## Reproduction
https://github.com/yf-yang/rsbuild-storybook-monorepo

## Steps
```
cd packages/pkg1
pnpm i
pnpm storybook
```
## Details
`@rsbuild/plugin-source-build` is used in a monorepo. However, the dependency package `pkg2` could not be correctly resolved. I've hooked source build plugin code. If I got it right, the packages/tsconfig references are correctly configured.

Did I miss something and configure something wrong, or is this a bug?

## Additional information

https://github.com/yf-yang/rsbuild-storybook-monorepo/blob/main/patches/%40rsbuild__plugin-source-build%400.7.9.patch#L9-L10

This is another bug (rule.resolve.conditionNames is not initialized, so it is actually `undefined`).

**Comment by fi3ework** [comment]
This is raised when combining @rsbuild/plugin* 0.7 with storybook's rsbuild 0.6 with cause an incompatible. When downgrade plugin to 0.6, there's another issue. I'll try to bump storybook's rsbuild to 0.7 first.

**Comment by yf-yang** [comment]
Updated reproduction to 0.0.6

**Comment by yf-yang** [comment]
Awesome, the reproduction is fine now. I'll give it a try with my own workspace and get back to you later.

BTW, it modern.js up to date with those settings? Currently I use rsbuild-storybook separately because seems there are still many problems when using modern.js with storybook8.

**Comment by fi3ework** [comment]
Modern.js is still only works with SB7, we hope to migrate projects to storybook-rsbuild from SB8 and future versions.

**Comment by yf-yang** [comment]
Thanks, it runs well.
