### ISSUE TITLE
Support for --webpack-stats-json

### ISSUE THREAD

**Issue by matheusmichels** [rspack-contrib/storybook-rsbuild#26]
Hey everyone! First of all, thanks for this nice plugin!

I was wondering if I would still be able to output a stats file by using it, as I currently do with Webpack, by running `storybook build --webpack-stats-json`.
Is that supported?

**Comment by fi3ework** [comment]
Yes, `--webpack-stats-json` is superseded by `--stats-json` in Storybook. We already support stats. Here's a screencap of the example in this repository.

```
pnpm build:storybook --stats-json
```

<img width="553" alt="Code 2024-06-25 23 01 19" src="https://github.com/rspack-contrib/storybook-rsbuild/assets/12322740/53abce22-b1c5-45ec-a02f-52fbb5d86793">

Have a try.

**Comment by fi3ework** [comment]
Sorry, I didn't realize that the stats support wasn't on a release version before. I just released a new version, have a try.
