### ISSUE TITLE
Non-story files should not be processed

### ISSUE THREAD

**Issue by tmkx** [rspack-contrib/storybook-rsbuild#31]
Reproduction:

1. add `./src/stories/Button.spec.tsx` with content: `this file should not be included`
2. pnpm storybook
3. "Compile error: Module build failed"

**Comment by fi3ework** [comment]
It's an known issue with rspack still lacks supports of `webpackInclude` magic comment. Check troubleshooting on README for the workaround.

**Comment by fi3ework** [comment]
Fixed in 0.0.7 as Rspack has support `webpackInclude` magic comment.
