### ISSUE TITLE
`Conflict: Multiple assets emit different content to the same filename iframe.html` when using custom `source.entry`

### ISSUE THREAD

**Issue by jeffijoe** [rspack-contrib/storybook-rsbuild#50]
Firstly, thank you for making this! I have been migrating from Vite to Rsbuild because of numerous issues with Vite and it has been smooth sailing for the most part. 🙌 

## Problem

In my `rsbuild.config.ts`, I have the following:

```ts
tools: {
  htmlPlugin: false,
},
source: {
  entry: {
    index: './src/client/main.tsx',
  },
},
```

This is because I don't use the `index.html` provided by Rsbuild and instead render the script tags in my backend.

However, this results in `Conflict: Multiple assets emit different content to the same filename iframe.html` when running Storybook.

## Workaround

Adding the following to the Storybook config make the error go away:

```
rsbuildFinal(config) {
  delete config.source.entry.index
  return config
},
```

**Comment by fi3ework** [comment]
Duplicated with #https://github.com/rspack-contrib/storybook-rsbuild/issues/43

**Comment by jeffijoe** [comment]
Sorry about that @fi3ework ! I only looked through open issues and googling the error only led me to unrelated Webpack issues. Happy to hear it's already resolved, great work! 🙏

**Comment by fi3ework** [comment]
Glad you're adopting Rspack based tools. Thanks for support.
