### ISSUE TITLE
Creating new stories and saving stories in UI is not currently supported?

### ISSUE THREAD

**Issue by jeffijoe** [rspack-contrib/storybook-rsbuild#51]
After switching to `storybook-rsbuild`, the `Save` functionality in the Storybook UI stopped working:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/f1b78e3e-b6fb-4873-8768-0781ca8a9d8d">

The `+` button to [create a new story](https://storybook.js.org/docs/get-started/whats-a-story#create-a-new-story) is also not available:

<img width="302" alt="image" src="https://github.com/user-attachments/assets/ff9f4522-2bb8-4880-b59c-f43c1a4ee3af">

**Comment by fi3ework** [comment]
Which version of storybook are you using. In the project's sandbox, these functionality works whereas they're in different UI (8.2.1).
<img width="1850" alt="image" src="https://github.com/user-attachments/assets/5de17cfe-d93c-47e5-9aeb-e71ae9a9fce0">

**Comment by jeffijoe** [comment]
I'm on Storybook 8.2.5. I can get the `Create new story` (within an existing `.stories.tsx`) UI to show, but it won't save.

**Comment by fi3ework** [comment]
I took a look into the source code. The new button will show when https://github.com/storybookjs/storybook/blob/next/code/core/src/builder-manager/utils/framework.ts/#L38 is `true`, and `extractProperRendererNameFromFramework` can only detect enumerated frameworks here (https://github.com/storybookjs/storybook/blob/next/code/core/src/common/utils/get-storybook-info.ts#L30-L49). The solution is to add `storybook-react-rsbuild` and `storybook-vue3-rsbuild` to Storybook's monorepo.

**Comment by fi3ework** [comment]
>  the Save functionality in the Storybook UI stopped working:

Could you provide a minimal reproduction? It at least works in sandbox https://github.com/user-attachments/assets/3c9aa21f-a350-49ef-9ea3-9f57ed6d5a37.

**Comment by jeffijoe** [comment]
Turns out the `Save` just required a restart of Storybook. 👍 

So I guess we need to open a PR with Storybook to add the Rsbuild framework to their known list?

**Comment by fi3ework** [comment]
Yes, I'm opening the PR to add the frameworks.

**Comment by JReinhold** [comment]
I have confirmed that this now works in the latest Storybook 8.3.0 prereleases (if you apply the workaround described in #76)

![image](https://github.com/user-attachments/assets/649060e2-6993-4ca4-8e01-c06afabc5615)


🚀

**Comment by fi3ework** [comment]
Closing this as it has been resolved, and will be shipped with Storybook 8.3.0. 🥳
