### ISSUE TITLE
`public/index.html` gets copied instead of the Storybook template when building

### ISSUE THREAD

**Issue by Atmos4** [rspack-contrib/storybook-rsbuild#65]
When running `storybook build`, if there is an HTML template located at `public/index.html`, it is copied to the `storybook-static` instead of the correct storybook HTML entrypoint.

Example repo: https://github.com/Atmos4/rsbuild-storybook-demo/tree/public-index-faulty-copy
Branch: `public-index-faulty-copy`.

Example configuration:
```ts
export default defineConfig({
  plugins: [pluginReact()],
  html: {
    template: "./public/index.html",
  },
});
```

## Expected behavior

The template file should be ignored. There shouldn't be any way to produce a corrupted storybook build.

**Comment by Atmos4** [comment]
The current fix I have is to just move my template file outside of `/public` folder. It works for me to do that, but I was wondering if there was a more elegant way to do it.

_Note: this might also be a Storybook bug. In that case I can repost this issue in the Storybook repo_

**Comment by fi3ework** [comment]
Checking, it might not be a Storybook's issue but rather the default merge behavior of Rsbuild. I also found that the build process won't exit after build (might be caused by Storybook's internal refactor).

**Comment by fi3ework** [comment]
To clarify, will `storybook:build` hang on your device after build success, or it's just a issue on my device?

**Comment by fi3ework** [comment]
All clear, I think it's telemetry blocked by some network proxy. 🥲

**Comment by Atmos4** [comment]
> will storybook:build hang on your device after build success

It doesn't do that on my device 😄

**Comment by Atmos4** [comment]
> rather the default merge behavior of Rsbuild

It might be the case. I can't really find any open similar issue on Storybook's side and I assume there would be one as the problem should be quite common.
