### ISSUE TITLE
v0.0.12 breaks dev

### ISSUE THREAD

**Issue by Atmos4** [rspack-contrib/storybook-rsbuild#70]
My guess is a regression problem when #65 and #66 were fixed.

Example repo for reproduction: https://github.com/Atmos4/rsbuild-storybook-demo/tree/wrong-asset-import

Issue: `storybook dev` ~~and `storybook build`~~ do not work anymore and generate broken static assets

**Comment by Atmos4** [comment]
Maybe the CI could be flavored with some e2e testing setup to make sure that the sandboxes keep working?

**Comment by fi3ework** [comment]
What does it look like to be unable to work?

**Comment by Atmos4** [comment]
Built version: 
![image](https://github.com/user-attachments/assets/2be8dbc4-e026-40cb-b733-89165acfe987)

Dev version (infinite loading)
![image](https://github.com/user-attachments/assets/a0830d32-1ddc-44d0-9183-b78d955e8c02)

The problem is solved when downgrading to 0.0.11

**Comment by fi3ework** [comment]
Introduced in https://github.com/rspack-contrib/storybook-rsbuild/pull/69. I'll fix it.

**Comment by Atmos4** [comment]
Thank you for being so responsive and so quick at fixing issues ⭐

**Comment by fi3ework** [comment]
Will it break at build as well? I tried to build and use `pnpx http-server storybook-static`, the website looks fine.

**Comment by Atmos4** [comment]
I will take another look at the build. I used LiveServer from VS Code which usually works, so I will try something else!

**Comment by Atmos4** [comment]
With `pnpx http-server storybook-static`, things work fine! Then I will stop using LiveServer for storybook 😇

**Comment by Atmos4** [comment]
@fi3ework dev works again after the fix 🎉 

However as far as I know #66 is still an issue 🤔 the proposed solution works for me, but I guess we can still count the issue as opened

**Comment by Atmos4** [comment]
I posted the updated issue and a fix I found in a new issue #72
