### ISSUE TITLE
Stories fail to load when hosting in a  subdirectory

### ISSUE THREAD

**Issue by dnwhte** [rspack-contrib/storybook-rsbuild#75]
Started in `storybook-react-rsbuild` version `0.0.12` and continues in `0.0.14`.

When hosting the storybook in a subdirectory (e.g. mysite.com/storybook) story assets fail to load because the request path is incorrect.

For example:

Expected request path: `http://mysite.com/storybook/static/js/async/767.a2a80d9a.iframe.bundle.js `
Actual request path: `http://mysite.com/static/js/async/767.a2a80d9a.iframe.bundle.js `

**Comment by fi3ework** [comment]
Could you try setting `https://rsbuild.dev/config/output/asset-prefix#outputassetprefix` as a workaround. I will check other official Storybook builder's behavior and make sure don't break https://github.com/rspack-contrib/storybook-rsbuild/pull/73.

**Comment by dnwhte** [comment]
I did give that a go. No change. The request path does not contain assetPrefix.

**Comment by sumy7** [comment]
I found this issue, but the solution provided does not work with the rsbuild configuration.
https://github.com/storybookjs/storybook/issues/1291

**Comment by fi3ework** [comment]
It was a legacy options and not work with current Storybook anymore, I'll check this issue tonight.

**Comment by sumy7** [comment]
I found a solution that seems to work well.
for example subpath is `/subpath/storybook/`

package.json
```
{
  "scripts": {
      "build-storybook": "storybook build -o dist/storybook",
      "postbuild-storybook": "perl -i -p -e \"s#import './subpath/storybook/#import './#\" ./dist/storybook/iframe.html"
  }
}
```

.storybook/main.ts
```
{
  rsbuildFinal: (config) => {
    // Customize the final Rsbuild config here
    config.output ||= {};
    config.output.assetPrefix = '/subpath/storybook/';
    return config;
  }
}
```

**Comment by cmdcolin** [comment]
glad to see this was fixed right as i ran into it :)

note: i am not fully aware of the issues that could result from relative paths but i found that assetPrefix 'auto' did not work in this scenario (it gave a browser error like this which was surprising https://stackoverflow.com/questions/64294706/webpack5-automatic-publicpath-is-not-supported-in-this-browser), so i used assetPrefix './' and it worked


```
  rsbuildFinal: config => {
    config.output ||= {}
    config.output.assetPrefix = './'
    return config
  },


```
ps: i have found the rsbuild+rspack experience to be very good, i converted a quite large codebase to use it very quickly and it worked much better than vite which struggled with various constructs like webworkers. thanks for your hard work on the project

**Comment by fi3ework** [comment]
It's a bit complex that mixing public path with Storybook, writing a fixed `/sub-path/` is the way I know to works fine in 0.0.15. If you find any bug, feel free to launch an issue. And, thanks for adopting the Rspack ecosystem, have fun.

**Comment by raDiesle** [comment]
False positive. Actually works as expected. I moved it into the rslib config, also works fine
